# Generated by Django 2.2.5 on 2019-09-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
        ('apicbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='recipe_favorited',
            field=models.ManyToManyField(to='manager.Recipe'),
        ),
    ]
