# Generated by Django 2.2.5 on 2019-09-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicbase', '0003_auto_20190904_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
