# Generated by Django 2.2.5 on 2019-09-03 02:26

from django.db import migrations
from manager.models import Unit


class Migration(migrations.Migration):

    def create_types(apps, schema_editor):
        db_alias = schema_editor.connection.alias
        for unit in Unit.UNIT_CHOICES:
            Unit.objects.using(db_alias).create(id=unit[0])

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_types),
    ]
