# Generated by Django 2.2.5 on 2019-09-03 02:26

from django.db import migrations


class Migration(migrations.Migration):

    def create_types(apps, schema_editor):
        KILOGRAM = 1
        GRAM = 2
        LITER = 3
        CENTILITER = 4
        UNIT_CHOICES = (
            (KILOGRAM, 'kg'),
            (GRAM, 'g'),
            (LITER, 'l'),
            (CENTILITER, 'cl'),
        )
        Unit = apps.get_model('manager', 'Unit')
        for unit in UNIT_CHOICES:
            Unit.objects.create(id=unit[0])

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_types),
    ]
