# Generated by Django 2.2.5 on 2019-09-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20190903_0226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='article_number',
            field=models.IntegerField(),
        ),
    ]
